#### 넘파이(Numpy)
- pandas, 머신러닝 라이브러리에서 기본적으로 필요한 라이브러리
- 파이썬 list 보다 빠름 / 메모리는 적게 사용
- 빌트인 함수 : 선형대수, 통계 관련 여러 함수 내장
- numpy 데이터 구조
    - ndarray

In [1]:
import numpy as np

In [2]:
# 1차원 벡터 생성
array1 = np.array([1,2,3])
array1

array([1, 2, 3])

In [ ]:
print(type(array1))
print(array1.shape) # (3, ) : 3열 (1차원 배열이기에 행열 정보 없음)

<class 'numpy.ndarray'>
(3,)


In [5]:
# 2차원

array2 = np.array([[1,2,3],[4,5,6]])
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(type(array2))
print(array2.shape) # (2,3) 2행 3열

<class 'numpy.ndarray'>
(2, 3)


In [ ]:
array2 = np.array([[1,2,3]])
print(array2)
print(array2.shape) # (1,3) 1행 3열

[[1 2 3]]
(1, 3)


In [9]:
# 파이썬 리스트
list1 = [1, 2, 'a', 'b', True]
list1

[1, 2, 'a', 'b', True]

In [ ]:
array1.dtype # int64 ( int, byte )

dtype('int64')

In [ ]:
array3 = np.array([1,2,3.1])
print(array3.dtype) # float64 -> float로 잡는다. 

float64


In [ ]:
array4 = np.array(list1)
print(array4.dtype) # <U21

<U21


- ndarray 다양한 방법으로 생성하기

In [ ]:
# arange(숫자) / arange(시작값, 숫자)
np.arange(10)
np.arange(5, 10)
np.arange(1,10,2) # array([1, 3, 4, 7, 9])

array([1, 3, 5, 7, 9])

In [ ]:
# zeros 0으로 채우기
# dtype 지정 안 하는 경우 float
# int32 / int64 -> int64 = 8 bite(사용용량) 사용
np.zeros(5, dtype="int32")

array([0., 0., 0., 0., 0.])

In [17]:
# ones 1로 채우기
np.ones(5, dtype="int32")

array([1, 1, 1, 1, 1], dtype=int32)

In [ ]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [19]:
np.ones((3,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [ ]:
# full - 특정 숫자로 채우기
np.full((3,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [ ]:
# eye - 단위행렬
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# linspace - 처음값(고정) - 끝값(고정) 사이에 랜덤한 숫자 출력
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

- 차원 변경 : reshape()
- 1차원 <--> 2차원

In [ ]:
# 1차원 (1 * 10)
array1 = np.arange(10)
print(array1)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# 1 -> 2 (5 * 2)
array1.reshape(5,2) # 개수가 맞아야 한다. 

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [26]:
# 열(5)만 지정, 행은 알아서 지정
array1.reshape(-1, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [27]:
array1.reshape(5,-1)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [28]:
# 임의의 수 ndarray 생성

np.random.rand(2,3)

array([[0.51466648, 0.13502231, 0.4055381 ],
       [0.67188662, 0.47988402, 0.82354072]])

In [ ]:
# 임의의 ndarray : 정규 분포

np.random.randn(2,3)

array([[-0.24648503, -0.88095046,  0.16954654],
       [-0.41897252,  0.62746259, -1.74290155]])

In [30]:
# 1 - 10 사이의 임의 수
np.random.randint(1,10,5)

array([8, 4, 4, 5, 1], dtype=int32)

In [31]:
np.random.randint(1,100,(5,4))

array([[80, 24, 96, 24],
       [54, 90, 17, 29],
       [87, 74, 17, 64],
       [38, 83, 81, 68],
       [39, 14, 62, 38]], dtype=int32)

In [34]:
np.random.randn(3,4)

array([[-0.35184408, -0.43798232, -0.48436622, -0.93246979],
       [ 0.61480148, -1.70595664,  0.03299618,  1.12847349],
       [ 1.49261808, -0.940476  ,  0.93758606, -0.32965529]])

In [41]:
# seed
# random 으로 생성해도 동일한 결과를 나오게 하고 싶음

np.random.seed(42) # 숫자는 아무거나 상관없음
np.random.randn(3,4)

array([[ 0.49671415, -0.1382643 ,  0.64768854,  1.52302986],
       [-0.23415337, -0.23413696,  1.57921282,  0.76743473],
       [-0.46947439,  0.54256004, -0.46341769, -0.46572975]])

In [44]:
# 인덱싱, 슬라이싱

array1 = np.arange(1,10) 
array1[-1]

np.int64(9)

In [ ]:
# slice 활용 1.
array1[:3]

array([1, 2, 3])

In [ ]:
# slice 활용 2
array2 = array1.reshape(3,3)
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
array2[[0,1],2]

array([3, 6])

In [49]:
array1[array1 > 5]

array([6, 7, 8, 9])

In [ ]:
list1 = list(range(10)) # normal python list
list1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [51]:
# list[list1 > 5] # normal python list [ > ] -> NOT work.
array1[array1 > 5] # only Numpy list [ > ] -> Work 

array([6, 7, 8, 9])

In [52]:
# 행렬 사칙연산

x = np.array([[4,4,4],[8,8,8]])
y = np.array([[1,1,1],[2,2,2]])

In [53]:
x + y

array([[ 5,  5,  5],
       [10, 10, 10]])

In [54]:
x - y

array([[3, 3, 3],
       [6, 6, 6]])

In [55]:
x * y

array([[ 4,  4,  4],
       [16, 16, 16]])

In [56]:
x // y

array([[4, 4, 4],
       [4, 4, 4]])

In [57]:
x * 10

array([[40, 40, 40],
       [80, 80, 80]])

In [58]:
# 행렬 내접의 곱

x = np.array([[1,2,3],[4,5,6]])
y = np.array([[7,8],[9,10],[11,12]])
print(x)
print(y)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


In [ ]:
# dot으로 행렬 연산자 곱 -> ? 어떻게?
np.dot(x,y)

array([[ 58,  64],
       [139, 154]])

In [ ]:
# 전치행렬(행렬 뒤바꾸기)

np.transpose(x)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
v = np.array([3,4])

# norm(ord = Norm의 종류)
# L1(Manhattan distnace), L2(Euclidean distance), Max(절댓값 중 가장 큰 값)
# (Default/Common) L2
np.linalg.norm(v)

np.float64(5.0)

In [ ]:
np.linalg.norm(v)